import { Hono } from 'hono'
import { validator } from 'hono/validator'
import { buildClassifyFolderMessage, buildDescriptionMessage, buildTagWithIconMessage, classifyFolderByOpenAI, generateDescriptionByOpenAI, generateTagsWithIconByOpenAI, isNil, isNotNil, isNumberString, parseClassifyFolderResponse, parseTagsWithIcon } from '@web-archive/shared/utils'
import { z } from 'zod'
import type { HonoTypeUserInformation } from '~/constants/binding'
import result from '~/utils/result'
import { clearDeletedPage, deletePageById, filterLivePageIds, getFtsContentByIds, getMaxLastChecked, getPageById, getPageVersionById, getSearchPagesByIds, hardDeletePages, insertPage, insertPageVersion, purgeExpiredDeletedPages, queryAllPageIds, queryDeletedPage, queryPage, queryPageByUrl, queryPageVersions, queryPagesForClassify, queryPagesForRecheck, queryPagesForReindex, queryRecentSavePage, restorePage, searchPageIdsByKeyword, selectPageTotalCount, updatePage, updatePageContent, updatePageDescription, updatePageFolderId, updatePagesLinkStatus, upsertPageFts } from '~/model/page'
import { getFolderById, insertFolder, restoreFolder, selectAllFolders } from '~/model/folder'
import { getAITagConfig } from '~/model/store'
import { getFileFromBucket, removeBucketFile, saveFileToBucket } from '~/utils/file'
import { htmlToText } from '~/utils/htmlToText'
import { updateShowcase } from '~/model/showcase'
import { bindPageTagsWithIcon, getAllTagNames, selectAllTags, updateBindPageByTagName } from '~/model/tag'
import type { LinkStatus } from '~/sql/types'

const app = new Hono<HonoTypeUserInformation>()

// After a page is saved, use the configured AI to (1) write a description from the
// page's own text, (2) assign emoji tags, reusing the existing tag vocabulary, and
// (3) when the upload opted in via aiClassifyFolder, move the page into an AI-picked folder.
// Best-effort: runs via waitUntil so it never blocks the upload, and leaves things
// untouched on any failure or when AI isn't configured.
async function autoEnrichPage(env: { DB: D1Database, AI: any }, pageId: number, title: string, content: string, options?: { aiClassifyFolder: boolean, currentFolderId: number }) {
  if (!content?.trim())
    return

  let config
  try {
    config = await getAITagConfig(env.DB)
  }
  catch {
    return
  }
  // enabled is a later addition: configs saved before it exists count as enabled.
  if (config.enabled === false)
    return
  if (!config.model)
    return
  if (config.type === 'openai' && (!config.baseUrl || !config.apiKey))
    return
  if (config.type === 'cloudflare-gateway' && (!config.baseUrl || !config.gatewayToken))
    return

  // Sequential (not Promise.all) to avoid two concurrent D1 writes racing.
  await autoGenerateDescription(env, config, pageId, title, content)
  await autoGenerateTags(env, config, pageId, title, content)
  if (options?.aiClassifyFolder)
    await autoClassifyFolder(env, config, pageId, title, content, options.currentFolderId)
}

async function autoGenerateDescription(env: { DB: D1Database, AI: any }, config: any, pageId: number, title: string, content: string) {
  try {
    let description = ''
    if (config.type === 'openai' || config.type === 'cloudflare-gateway') {
      description = await generateDescriptionByOpenAI({
        model: config.model,
        baseUrl: config.baseUrl,
        apiKey: config.apiKey,
        gatewayToken: config.gatewayToken,
        title,
        content,
        tagLanguage: config.tagLanguage,
      })
    }
    else {
      const res = await env.AI.run(config.model, {
        messages: buildDescriptionMessage({ title, content, tagLanguage: config.tagLanguage }),
      })
      description = typeof res?.response === 'string' ? res.response.trim() : ''
    }

    if (description)
      await updatePageDescription(env.DB, pageId, description)
  }
  catch (error) {
    console.error('Failed to auto-generate page description', error)
  }
}

async function autoGenerateTags(env: { DB: D1Database, AI: any }, config: any, pageId: number, title: string, content: string) {
  try {
    // Feed the current tag names as preferred so the model reuses them.
    const preferredTags = await getAllTagNames(env.DB).catch(() => [] as string[])
    let tags: Array<{ name: string, icon: string }> = []
    if (config.type === 'openai' || config.type === 'cloudflare-gateway') {
      tags = await generateTagsWithIconByOpenAI({
        model: config.model,
        baseUrl: config.baseUrl,
        apiKey: config.apiKey,
        gatewayToken: config.gatewayToken,
        title,
        content,
        tagLanguage: config.tagLanguage,
        preferredTags,
      })
    }
    else {
      const res = await env.AI.run(config.model, {
        messages: buildTagWithIconMessage({ title, content, tagLanguage: config.tagLanguage, preferredTags }),
      })
      tags = typeof res?.response === 'string' ? parseTagsWithIcon(res.response) : []
    }

    if (tags.length > 0)
      await bindPageTagsWithIcon(env.DB, pageId, tags)
  }
  catch (error) {
    console.error('Failed to auto-generate page tags', error)
  }
}

// One AI folder-classification call across the three provider types. Returns null
// when the answer can't be parsed (Workers AI path; the OpenAI-compatible path throws).
// A parsed answer may itself carry folder: null = "no fitting destination".
async function classifyFolder(env: { AI: any }, config: any, page: { title: string, pageDesc: string }, folderNames: string[]): Promise<{ folder: string | null, isNew: boolean } | null> {
  if (config.type === 'openai' || config.type === 'cloudflare-gateway') {
    return await classifyFolderByOpenAI({
      type: config.type,
      model: config.model,
      baseUrl: config.baseUrl,
      apiKey: config.apiKey,
      gatewayToken: config.gatewayToken,
      title: page.title,
      pageDesc: page.pageDesc,
      folderNames,
      tagLanguage: config.tagLanguage,
    })
  }
  const res = await env.AI.run(config.model, {
    messages: buildClassifyFolderMessage({ title: page.title, pageDesc: page.pageDesc, folderNames, tagLanguage: config.tagLanguage }),
  })
  return typeof res?.response === 'string' ? parseClassifyFolderResponse(res.response) : null
}

// Third enrichment step (opt-in via the upload's aiClassifyFolder flag): let the AI
// pick a folder — preferring existing ones, creating a new one only when the model
// says none fits — and move the page there. Best-effort like the other steps: any
// failure or unusable answer leaves the page in the folder it was saved to.
async function autoClassifyFolder(env: { DB: D1Database, AI: any }, config: any, pageId: number, title: string, content: string, currentFolderId: number) {
  try {
    const folders = await selectAllFolders(env.DB)
    const answer = await classifyFolder(env, config, { title, pageDesc: content }, folders.map(folder => folder.name))
    // No parseable answer, or the model said nothing fits: stay in the fallback folder.
    if (!answer || answer.folder === null)
      return
    const answerFolder = answer.folder
    const match = folders.find(folder => folder.name.toLowerCase() === answerFolder.toLowerCase())
    let targetFolderId: number
    if (match)
      targetFolderId = match.id
    else if (answer.isNew)
      targetFolderId = await insertFolder(env.DB, answerFolder)
    else
      return
    if (targetFolderId !== currentFolderId)
      await updatePageFolderId(env.DB, pageId, targetFolderId)
  }
  catch (error) {
    console.error('Failed to auto-classify page folder', error)
  }
}

app.post(
  '/upload_new_page',
  validator('form', (value, c) => {
    if (!value.title || typeof value.title !== 'string') {
      return c.json(result.error(400, 'Title is required'))
    }
    if (value.pageDesc && typeof value.pageDesc !== 'string') {
      return c.json(result.error(400, 'Description should be a string'))
    }
    if (!value.pageUrl || typeof value.pageUrl !== 'string') {
      return c.json(result.error(400, 'URL is required'))
    }
    if (!value.pageFile) {
      return c.json(result.error(400, 'File is required'))
    }
    if (!value.folderId || !isNumberString(value.folderId)) {
      return c.json(result.error(400, 'FolderId id should be a number'))
    }

    if (isNotNil(value.isShowcased) && !isNumberString(value.isShowcased)) {
      return c.json(result.error(400, 'isShowcased is required'))
    }

    if (isNotNil(value.bindTags)) {
      if (typeof value.bindTags !== 'string')
        return c.json(result.error(400, 'bindTags should be a string array'))
      try {
        const bindTags = JSON.parse(value.bindTags)
        if (!Array.isArray(bindTags))
          return c.json(result.error(400, 'bindTags should be a string array'))
      }
      catch (e) {
        return c.json(result.error(400, 'bindTags should be a string array'))
      }
    }

    // saveMode controls behaviour when the URL is already archived:
    //   'new'       -> always create a new entry (default / legacy behaviour)
    //   'overwrite' -> replace targetPageId's content, discard the old snapshot
    //   'version'   -> archive targetPageId's current content, then replace it
    const saveMode = value.saveMode === 'overwrite' || value.saveMode === 'version'
      ? value.saveMode
      : 'new'

    return {
      title: value.title,
      pageDesc: value.pageDesc as string,
      pageUrl: value.pageUrl,
      pageFile: value.pageFile,
      folderId: Number(value.folderId),
      screenshot: value.screenshot,
      bindTags: JSON.parse(value.bindTags ?? '[]') as string[],
      isShowcased: Boolean(Number(value.isShowcased ?? 0)),
      saveMode: saveMode as 'new' | 'overwrite' | 'version',
      targetPageId: isNumberString(value.targetPageId) ? Number(value.targetPageId) : undefined,
      // Form fields arrive as strings; the plugin sends '1' (or 'true') to opt in.
      aiClassifyFolder: value.aiClassifyFolder === '1' || value.aiClassifyFolder === 'true',
    }
  }),
  async (c) => {
    const { title, pageDesc = '', pageUrl, pageFile, folderId, screenshot, bindTags, isShowcased, saveMode, targetPageId, aiClassifyFolder } = c.req.valid('form')

    // todo check folder exists?

    const [contentUrl, screenshotId] = await Promise.all([
      saveFileToBucket(c.env.BUCKET, pageFile),
      saveFileToBucket(c.env.BUCKET, screenshot),
    ])

    if (isNil(contentUrl)) {
      return c.json({ status: 'error', message: 'Failed to upload file' })
    }

    // Extract searchable text once; reused across all save modes for FTS.
    let content = ''
    try {
      const html = typeof pageFile === 'string' ? pageFile : await (pageFile as File).text()
      content = htmlToText(html)
    }
    catch (error) {
      console.error('Failed to extract page text', error)
    }

    // Overwrite / new-version: mutate an existing page instead of inserting.
    if (saveMode !== 'new' && isNotNil(targetPageId)) {
      const existing = await getPageById(c.env.DB, { id: targetPageId, isDeleted: false })
      if (isNil(existing)) {
        return c.json(result.error(404, 'Target page not found'))
      }

      if (saveMode === 'version') {
        // Keep the current capture as a historical snapshot (its R2 objects stay).
        await insertPageVersion(c.env.DB, existing)
      }
      else {
        // Overwrite: the old capture is discarded, so free its R2 objects.
        await removeBucketFile(c.env.BUCKET, [existing.contentUrl, existing.screenshotId].filter(isNotNil) as string[])
      }

      const updated = await updatePageContent(c.env.DB, { id: targetPageId, title, pageDesc, contentUrl, screenshotId })
      if (!updated) {
        return c.json(result.error(500, 'Failed to update page'))
      }

      try {
        await upsertPageFts(c.env.DB, { pageId: targetPageId, title, pageDesc, content })
      }
      catch (error) {
        console.error('Failed to index page for full-text search', error)
      }
      await updateBindPageByTagName(c.env.DB, bindTags.map(tagName => ({ tagName, pageIds: [targetPageId] })), [])
      c.executionCtx.waitUntil(autoEnrichPage(c.env, targetPageId, title, content, { aiClassifyFolder, currentFolderId: existing.folderId }))
      return c.json(result.success(null))
    }

    const insertId = await insertPage(c.env.DB, {
      title,
      pageDesc,
      pageUrl,
      contentUrl,
      folderId,
      screenshotId,
      isShowcased,
    })
    if (isNotNil(insertId)) {
      // Index the page for full-text search (best-effort; a failure here must not
      // fail the upload — the page can be re-indexed later via /reindex).
      try {
        await upsertPageFts(c.env.DB, { pageId: insertId, title, pageDesc, content })
      }
      catch (error) {
        console.error('Failed to index page for full-text search', error)
      }

      c.executionCtx.waitUntil(autoEnrichPage(c.env, insertId, title, content, { aiClassifyFolder, currentFolderId: folderId }))

      const updateTagResult = await updateBindPageByTagName(c.env.DB, bindTags.map(tagName => ({ tagName, pageIds: [insertId] })), [])
      if (updateTagResult)
        return c.json(result.success(null))
    }
    return c.json(result.error(500, 'Failed to insert page'))
  },
)

app.post(
  '/query',
  validator('json', (value, c) => {
    if (isNotNil(value.folderId) && !isNumberString(value.folderId)) {
      return c.json(result.error(400, 'Folder ID should be a number'))
    }

    if (isNotNil(value.tagId) && !isNumberString(value.tagId)) {
      return c.json(result.error(400, 'Tag ID should be a number'))
    }

    if (value.pageNumber && !isNumberString(value.pageNumber)) {
      return c.json(result.error(400, 'Page number should be a number'))
    }

    if (value.pageSize && !isNumberString(value.pageSize)) {
      return c.json(result.error(400, 'Page size should be a number'))
    }

    if (isNotNil(value.linkStatus) && !['live', 'dead', 'redirect', 'unknown'].includes(value.linkStatus)) {
      return c.json(result.error(400, 'linkStatus should be one of live, dead, redirect, unknown'))
    }

    if (isNotNil(value.sort) && !['newest', 'oldest'].includes(value.sort)) {
      return c.json(result.error(400, 'sort should be one of newest, oldest'))
    }

    return {
      folderId: isNotNil(value.folderId) ? Number(value.folderId) : undefined,
      tagId: isNotNil(value.tagId) ? Number(value.tagId) : undefined,
      pageNumber: isNotNil(value.pageNumber) ? Number(value.pageNumber) : undefined,
      pageSize: isNotNil(value.pageSize) ? Number(value.pageSize) : undefined,
      keyword: value.keyword,
      startAt: isNotNil(value.startAt) ? String(value.startAt) : undefined,
      endAt: isNotNil(value.endAt) ? String(value.endAt) : undefined,
      linkStatus: isNotNil(value.linkStatus) ? value.linkStatus as LinkStatus : undefined,
      sort: isNotNil(value.sort) ? value.sort as 'newest' | 'oldest' : undefined,
    }
  }),
  async (c) => {
    const { folderId, pageNumber, pageSize, keyword, tagId, startAt, endAt, linkStatus, sort } = c.req.valid('json')

    const [pages, total] = await Promise.all([
      queryPage(
        c.env.DB,
        { folderId, pageNumber, pageSize, keyword, tagId, startAt, endAt, linkStatus, sort },
      ),
      selectPageTotalCount(c.env.DB, { folderId, keyword, tagId, startAt, endAt, linkStatus }),
    ])
    return c.json(result.success({ list: pages, total }))
  },
)

// Snippet window sizes around the first keyword hit (design spec: ~46 chars of
// context before, ~92 after; leading/trailing ellipses are added by the frontend).
const SNIPPET_BEFORE_LEN = 46
const SNIPPET_AFTER_LEN = 92
const SNIPPET_FALLBACK_LEN = 140

// Locate the keyword case-insensitively in the page text (body first, then the
// description — a description hit is still a 'content' match). FTS trigram
// folds case the same way for ASCII; for exotic foldings where JS can't find
// the hit again, fall back to the head of the text with an empty match.
function buildSnippet(content: string, pageDesc: string, keyword: string) {
  const lowerKeyword = keyword.toLowerCase()
  for (const text of [content, pageDesc]) {
    const index = text.toLowerCase().indexOf(lowerKeyword)
    if (index !== -1) {
      return {
        before: text.slice(Math.max(0, index - SNIPPET_BEFORE_LEN), index),
        match: text.slice(index, index + keyword.length),
        after: text.slice(index + keyword.length, index + keyword.length + SNIPPET_AFTER_LEN),
      }
    }
  }
  return { before: '', match: '', after: (content || pageDesc).slice(0, SNIPPET_FALLBACK_LEN) }
}

// Full-text search across titles, page content and tag names, deduped with
// matchType priority title > content > tag. `total` is the exact number of
// distinct matched non-deleted page ids across the three sources (pages that
// were never FTS-indexed can only surface via tag matches).
app.post(
  '/search',
  validator('json', (value, c) => {
    const schema = z.object({
      keyword: z.string({ message: 'Keyword is required' }).trim().min(1, 'Keyword is required'),
      pageNumber: z.number().int().positive().default(1),
      pageSize: z.number().int().positive().max(100).default(50),
    })
    const parsed = schema.safeParse(value ?? {})
    if (!parsed.success) {
      return c.json(result.error(400, parsed.error.errors[0]?.message ?? 'Invalid request'))
    }
    return parsed.data
  }),
  async (c) => {
    const { keyword, pageNumber, pageSize } = c.req.valid('json')

    // All tags are needed anyway to attach tag names to every result, so tag
    // matching is done in JS over the same list instead of a LIKE query.
    const [titleIds, contentIds, allTags] = await Promise.all([
      searchPageIdsByKeyword(c.env.DB, keyword, 'title'),
      searchPageIdsByKeyword(c.env.DB, keyword, 'content'),
      selectAllTags(c.env.DB),
    ])

    const lowerKeyword = keyword.toLowerCase()
    const tagCandidateIds: number[] = []
    const seenTagPageIds = new Set<number>()
    for (const tag of allTags) {
      if (!tag.name.toLowerCase().includes(lowerKeyword))
        continue
      for (const pageId of tag.pageIds) {
        if (!seenTagPageIds.has(pageId)) {
          seenTagPageIds.add(pageId)
          tagCandidateIds.push(pageId)
        }
      }
    }
    // pageIdDict may reference soft-deleted/purged pages; keep only live ones.
    const tagIds = await filterLivePageIds(c.env.DB, tagCandidateIds)

    const matchTypeById = new Map<number, 'title' | 'content' | 'tag'>()
    const orderedIds: number[] = []
    const collect = (ids: number[], matchType: 'title' | 'content' | 'tag') => {
      for (const id of ids) {
        if (!matchTypeById.has(id)) {
          matchTypeById.set(id, matchType)
          orderedIds.push(id)
        }
      }
    }
    collect(titleIds, 'title')
    collect(contentIds, 'content')
    collect(tagIds, 'tag')

    const total = orderedIds.length
    const offset = (pageNumber - 1) * pageSize
    const windowIds = orderedIds.slice(offset, offset + pageSize)

    const pageRows = await getSearchPagesByIds(c.env.DB, windowIds)
    const pageById = new Map(pageRows.map(page => [page.id, page]))

    // Page text is fetched only for the content matches in this window.
    const contentMatchedIds = windowIds.filter(id => matchTypeById.get(id) === 'content')
    const contentRows = await getFtsContentByIds(c.env.DB, contentMatchedIds)
    const contentById = new Map(contentRows.map(row => [row.id, row.content]))

    const list = windowIds
      .map((id) => {
        const page = pageById.get(id)
        if (isNil(page))
          return null
        const matchType = matchTypeById.get(id)!
        return {
          ...page,
          matchType,
          tags: allTags.filter(tag => tag.pageIds.includes(id)).map(tag => tag.name),
          ...(matchType === 'content'
            ? { snippet: buildSnippet(contentById.get(id) ?? '', page.pageDesc, keyword) }
            : {}),
        }
      })
      .filter(isNotNil)

    return c.json(result.success({ list, total }))
  },
)

app.post(
  '/query_all_page_ids',
  validator('json', (value, c) => {
    const schema = z.object({
      folderId: z.number({
        message: 'Folder ID should be a number',
      }),
    })

    const parsed = schema.safeParse(value)
    if (!parsed.success) {
      return c.json(result.error(400, parsed.error.errors[0].message))
    }

    return parsed.data
  }),
  async (c) => {
    const { folderId } = c.req.valid('json')
    const pages = await queryAllPageIds(c.env.DB, folderId)

    return c.json(result.success(pages))
  },
)

// Rebuild the full-text index from R2 for existing pages, in bounded batches.
// Call repeatedly, passing back the returned `cursor`, until `done` is true.
app.post(
  '/reindex',
  validator('json', (value, c) => {
    const schema = z.object({
      cursor: z.number().int().nonnegative().default(0),
      limit: z.number().int().positive().max(50).default(10),
    })
    const parsed = schema.safeParse(value ?? {})
    if (!parsed.success) {
      return c.json(result.error(400, parsed.error.errors[0]?.message ?? 'Invalid request'))
    }
    return parsed.data
  }),
  async (c) => {
    const { cursor, limit } = c.req.valid('json')
    const pages = await queryPagesForReindex(c.env.DB, { cursor, limit })

    let indexed = 0
    let failed = 0
    let lastId = cursor
    for (const page of pages) {
      lastId = page.id
      try {
        const object = await c.env.BUCKET.get(page.contentUrl)
        const html = object ? await object.text() : ''
        await upsertPageFts(c.env.DB, {
          pageId: page.id,
          title: page.title,
          pageDesc: page.pageDesc,
          content: htmlToText(html),
        })
        indexed++
      }
      catch (error) {
        console.error(`Failed to reindex page ${page.id}`, error)
        failed++
      }
    }

    return c.json(result.success({
      indexed,
      failed,
      cursor: lastId,
      done: pages.length < limit,
    }))
  },
)

const LINK_CHECK_TIMEOUT_MS = 8000
// Each probe is 1-2 outbound fetches; with the batch capped at 15 pages this
// stays far below the Worker's 50-subrequest budget.
const LINK_CHECK_CONCURRENCY = 5
const LINK_CHECK_MAX_LIMIT = 15

type ProbeResult = { status: LinkStatus, reason: 'cf-blocked' | null }

// A 403/503 carrying Cloudflare markers is CF challenging/blocking the probe,
// which says nothing about whether the page is alive for a real browser.
function isCloudflareBlocked(headers: Headers) {
  return headers.has('cf-mitigated')
    || headers.has('cf-ray')
    || (headers.get('server') ?? '').toLowerCase().includes('cloudflare')
}

// Conservative mapping — only clear signals produce a verdict, everything
// inconclusive is 'unknown' rather than a false 'dead':
//   2xx -> live; 3xx -> redirect; 404/410 -> dead;
//   403/503 behind Cloudflare -> unknown + 'cf-blocked'; other 4xx/5xx -> unknown.
function classifyLinkStatus(res: Response): ProbeResult {
  const { status } = res
  if (status >= 200 && status < 300)
    return { status: 'live', reason: null }
  if (status >= 300 && status < 400)
    return { status: 'redirect', reason: null }
  if (status === 404 || status === 410)
    return { status: 'dead', reason: null }
  if ((status === 403 || status === 503) && isCloudflareBlocked(res.headers))
    return { status: 'unknown', reason: 'cf-blocked' }
  return { status: 'unknown', reason: null }
}

// HEAD first (cheap); fall back to GET when the server rejects HEAD (405/501)
// or the HEAD attempt itself fails. Redirects are reported, not followed.
async function probeLink(pageUrl: string): Promise<ProbeResult> {
  // Only probe web URLs; malformed or non-http(s) strings are 'dead' without
  // spending any fetches.
  try {
    const { protocol } = new URL(pageUrl)
    if (protocol !== 'http:' && protocol !== 'https:')
      return { status: 'dead', reason: null }
  }
  catch {
    return { status: 'dead', reason: null }
  }
  const attempt = (method: 'HEAD' | 'GET') => fetch(pageUrl, {
    method,
    redirect: 'manual',
    signal: AbortSignal.timeout(LINK_CHECK_TIMEOUT_MS),
  })
  try {
    const res = await attempt('HEAD')
    if (res.status !== 405 && res.status !== 501)
      return classifyLinkStatus(res)
  }
  catch {
    // network error / timeout: retry once with GET below
  }
  try {
    const res = await attempt('GET')
    return classifyLinkStatus(res)
  }
  catch {
    // Both attempts threw (timeout / network error): no conclusion, not a dead verdict.
    return { status: 'unknown', reason: null }
  }
}

// Bounded worker pool; `next++` is race-free because workers only interleave at awaits.
async function mapWithConcurrency<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = Array.from({ length: items.length })
  let next = 0
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (next < items.length) {
      const index = next++
      results[index] = await fn(items[index])
    }
  })
  await Promise.all(workers)
  return results
}

// Manual link-health check over the archive, in bounded batches. Call
// repeatedly, passing back the returned `cursor`, until `done` is true
// (same cursor-loop protocol as /reindex).
app.post(
  '/recheck',
  validator('json', (value, c) => {
    const schema = z.object({
      folderId: z.number().int().optional(),
      cursor: z.number().int().nonnegative().default(0),
      limit: z.number().int().positive().max(LINK_CHECK_MAX_LIMIT).default(10),
    })
    const parsed = schema.safeParse(value ?? {})
    if (!parsed.success) {
      return c.json(result.error(400, parsed.error.errors[0]?.message ?? 'Invalid request'))
    }
    return parsed.data
  }),
  async (c) => {
    const { folderId, cursor, limit } = c.req.valid('json')
    const pages = await queryPagesForRecheck(c.env.DB, { cursor, limit, folderId })

    const checked = await mapWithConcurrency(pages, LINK_CHECK_CONCURRENCY, async (page) => {
      const probe = await probeLink(page.pageUrl)
      return { id: page.id, linkStatus: probe.status, linkStatusReason: probe.reason }
    })
    const statuses = await updatePagesLinkStatus(c.env.DB, checked)

    return c.json(result.success({
      checked: pages.length,
      cursor: pages.length > 0 ? pages[pages.length - 1].id : cursor,
      done: pages.length < limit,
      statuses,
    }))
  },
)

// Most recent link probe across all non-deleted pages (for "上次检测" in the toolbar).
app.get('/link_check_status', async (c) => {
  const lastChecked = await getMaxLastChecked(c.env.DB)
  return c.json(result.success({ lastChecked }))
})

// One AI call per page, so batches stay much smaller than recheck's.
const AI_CLASSIFY_MAX_LIMIT = 5

// Batch AI folder classification ("AI 整理") over ONE folder: each of its pages
// is sorted into another existing folder — or a newly created one when the model
// says none fits — in bounded batches. folderId is required by design: the user
// runs this on a selected (e.g. uncategorized) folder, and already-sorted folders
// must stay untouched. The model may answer "no fitting destination", which
// leaves the page in place. Call repeatedly, passing back the returned `cursor`,
// until `done` is true (same cursor-loop protocol as /recheck).
app.post(
  '/ai_classify_folder',
  validator('json', (value, c) => {
    const schema = z.object({
      folderId: z.number({ message: 'Folder ID is required' }).int().nonnegative(),
      cursor: z.number().int().nonnegative().default(0),
      limit: z.number().int().positive().max(AI_CLASSIFY_MAX_LIMIT).default(3),
    })
    const parsed = schema.safeParse(value ?? {})
    if (!parsed.success) {
      return c.json(result.error(400, parsed.error.errors[0]?.message ?? 'Invalid request'))
    }
    return parsed.data
  }),
  async (c) => {
    const { folderId, cursor, limit } = c.req.valid('json')

    // Same config guards as autoEnrichPage, but surfaced as an error so the
    // frontend can toast once and stop the loop.
    let config
    try {
      config = await getAITagConfig(c.env.DB)
    }
    catch {
      return c.json(result.error(500, 'AI not configured'))
    }
    if (
      config.enabled === false
      || !config.model
      || (config.type === 'openai' && (!config.baseUrl || !config.apiKey))
      || (config.type === 'cloudflare-gateway' && (!config.baseUrl || !config.gatewayToken))
    ) {
      return c.json(result.error(500, 'AI not configured'))
    }

    const pages = await queryPagesForClassify(c.env.DB, { folderId, cursor, limit })
    const folders = await selectAllFolders(c.env.DB)
    const sourceFolder = folders.find(folder => folder.id === folderId)
    // Candidate destinations exclude the source folder itself (organizing it means
    // moving pages OUT of it). Case-insensitive lookup, extended as new folders are
    // created within the batch so later pages reuse them without a second creation.
    const folderByName = new Map(folders.filter(folder => folder.id !== folderId).map(folder => [folder.name.toLowerCase(), { id: folder.id, name: folder.name }]))

    let classified = 0
    let moved = 0
    let createdFolders = 0
    const results: Array<{ id: number, folderId: number, folderName: string, createdFolder: boolean }> = []
    // Sequential on purpose: one AI call per page, and D1 writes shouldn't race.
    for (const page of pages) {
      try {
        const answer = await classifyFolder(c.env, config, { title: page.title, pageDesc: page.pageDesc }, Array.from(folderByName.values(), folder => folder.name))
        // No parseable answer, the model said nothing fits, or it echoed the source
        // folder back (possibly as a "new" one): leave the page in place.
        if (!answer || answer.folder === null)
          continue
        if (sourceFolder && answer.folder.toLowerCase() === sourceFolder.name.toLowerCase())
          continue
        let target = folderByName.get(answer.folder.toLowerCase())
        let createdFolder = false
        if (!target) {
          // Unknown name without an isNew claim is an unusable answer: leave the page in place.
          if (!answer.isNew)
            continue
          const folderId = await insertFolder(c.env.DB, answer.folder)
          target = { id: folderId, name: answer.folder }
          folderByName.set(answer.folder.toLowerCase(), target)
          createdFolder = true
          createdFolders++
        }
        classified++
        if (target.id !== page.folderId) {
          await updatePageFolderId(c.env.DB, page.id, target.id)
          moved++
        }
        results.push({ id: page.id, folderId: target.id, folderName: target.name, createdFolder })
      }
      catch (error) {
        // Per-page best-effort: a failed classification skips the page, the batch goes on.
        console.error(`Failed to classify folder for page ${page.id}`, error)
      }
    }

    return c.json(result.success({
      classified,
      moved,
      createdFolders,
      cursor: pages.length > 0 ? pages[pages.length - 1].id : cursor,
      done: pages.length < limit,
      results,
    }))
  },
)

app.post(
  '/query_by_url',
  validator('json', (value, c) => {
    const errorMsg = {
      message: 'Page URL is required',
    }
    const schema = z.object({
      pageUrl: z.string(errorMsg).min(1, errorMsg),
    })

    const parsed = schema.safeParse(value)
    if (!parsed.success) {
      if (parsed.error.errors.length > 0) {
        return c.json(result.error(400, parsed.error.errors[0].message))
      }
      return c.json(result.error(400, 'Invalid request'))
    }

    return parsed.data
  }),
  async (c) => {
    const { pageUrl } = c.req.valid('json')
    const pages = await queryPageByUrl(c.env.DB, pageUrl)
    return c.json(result.success(pages))
  },
)

app.get('/recent_save', async (c) => {
  const pages = await queryRecentSavePage(c.env.DB)
  return c.json(result.success(pages))
})

app.get(
  '/detail',
  validator('query', (value, c) => {
    if (!value.id || Number.isNaN(Number(value.id))) {
      return c.json(result.error(400, 'ID is required'))
    }
    return {
      id: Number(value.id),
    }
  }),
  async (c) => {
    const { id } = c.req.valid('query')

    const page = await getPageById(c.env.DB, {
      id,
      isDeleted: false,
    })
    if (page) {
      return c.json(result.success(page))
    }

    return c.json(result.success(null))
  },
)

app.delete(
  '/delete_page',
  validator('query', (value, c) => {
    if (!value.id || Number.isNaN(Number(value.id))) {
      return c.json(result.error(400, 'ID is required'))
    }
    return {
      id: Number(value.id),
    }
  }),
  async (c) => {
    const { id } = c.req.valid('query')

    if (await deletePageById(c.env.DB, id)) {
      return c.json(result.success({ id }))
    }

    return c.json(result.error(500, 'Failed to delete page'))
  },
)

app.put(
  '/update_page',
  validator('json', (value, c) => {
    if (!value.id || Number.isNaN(Number(value.id))) {
      return c.json(result.error(400, 'ID is required'))
    }

    if (!isNumberString(value.folderId)) {
      return c.json(result.error(400, 'Folder ID should be a number'))
    }

    if (!value.title || typeof value.title !== 'string') {
      return c.json(result.error(400, 'Title is required'))
    }

    if (typeof value.isShowcased !== 'number') {
      return c.json(result.error(400, 'isShowcased is required'))
    }

    if (isNotNil(value.bindTags) && !Array.isArray(value.bindTags)) {
      return c.json(result.error(400, 'bindTags should be an array'))
    }

    if (isNotNil(value.unbindTags) && !Array.isArray(value.unbindTags)) {
      return c.json(result.error(400, 'removeTags should be an array'))
    }

    if (isNotNil(value.bindTagsWithIcon) && !Array.isArray(value.bindTagsWithIcon)) {
      return c.json(result.error(400, 'bindTagsWithIcon should be an array'))
    }

    return {
      id: Number(value.id),
      folderId: Number(value.folderId),
      title: value.title,
      isShowcased: value.isShowcased,
      pageDesc: value.pageDesc ?? '',
      pageUrl: value.pageUrl ?? '',
      bindTags: value.bindTags as string[] ?? [],
      unbindTags: value.unbindTags as string[] ?? [],
      bindTagsWithIcon: value.bindTagsWithIcon as Array<{ name: string, icon: string }> ?? [],
    }
  }),
  async (c) => {
    const { id, folderId, title, isShowcased, pageDesc, pageUrl, bindTags, unbindTags, bindTagsWithIcon } = c.req.valid('json')
    if (isNil(folderId))
      return c.json(result.success(null))

    const bindTagParams = bindTags.map(tagName => ({ tagName, pageIds: [id] }))
    const unbindTagParams = unbindTags.map(tagName => ({ tagName, pageIds: [id] }))
    const updateSuccess = await updatePage(c.env.DB, { id, folderId, title, isShowcased, pageDesc, pageUrl, bindTags: bindTagParams, unbindTags: unbindTagParams })
    if (updateSuccess) {
      // AI-generated tags from the edit dialog carry an emoji; bind them via the
      // icon-aware path (new tags get the icon, existing tags keep theirs).
      if (bindTagsWithIcon.length > 0)
        await bindPageTagsWithIcon(c.env.DB, id, bindTagsWithIcon)
      return c.json(result.success(null))
    }

    return c.json(result.error(500, 'Failed to update page'))
  },
)

app.post(
  '/query_deleted',
  async (c) => {
    // Lazy 30-day retention: purge expired trash before listing, so the
    // "kept for 30 days" copy stays true without a cron trigger. Best-effort —
    // a purge failure must not break the trash view.
    try {
      await purgeExpiredDeletedPages(c.env.DB, c.env.BUCKET)
    }
    catch (error) {
      console.error('Failed to purge expired deleted pages', error)
    }
    const pages = await queryDeletedPage(c.env.DB)
    return c.json(result.success(pages))
  },
)

// Permanently delete a single soft-deleted page (R2 objects incl. archived
// versions, FTS row, version rows, page row). Only works on pages in the trash.
app.delete(
  '/hard_delete',
  validator('query', (value, c) => {
    if (!value.id || Number.isNaN(Number(value.id))) {
      return c.json(result.error(400, 'ID is required'))
    }
    return {
      id: Number(value.id),
    }
  }),
  async (c) => {
    const { id } = c.req.valid('query')

    const page = await getPageById(c.env.DB, { id, isDeleted: true })
    if (isNil(page)) {
      return c.json(result.error(404, 'Page not found in trash'))
    }

    if (await hardDeletePages(c.env.DB, c.env.BUCKET, [id])) {
      return c.json(result.success({ id }))
    }
    return c.json(result.error(500, 'Failed to delete page'))
  },
)

app.post(
  '/restore_page',
  validator('json', (value, c) => {
    if (isNil(value.id) || !isNumberString(value.id)) {
      return c.json(result.error(400, 'ID is required and should be a number'))
    }

    if (isNotNil(value.folderId) && !isNumberString(value.folderId)) {
      return c.json(result.error(400, 'Folder ID should be a number'))
    }

    return {
      id: Number(value.id),
      folderId: isNotNil(value.folderId) ? Number(value.folderId) : undefined,
    }
  }),
  async (c) => {
    const { id, folderId } = c.req.valid('json')
    let pageFolderId = folderId
    if (isNil(pageFolderId)) {
      const page = await getPageById(c.env.DB, { id })
      if (isNil(page)) {
        return c.json(result.error(500, 'Page not found'))
      }

      pageFolderId = page.folderId
    }
    const folder = await getFolderById(c.env.DB, { id: pageFolderId })
    if (isNil(folder)) {
      return c.json(result.error(500, 'Folder not found'))
    }
    if (folder.isDeleted) {
      const restoreFolderResult = await restoreFolder(c.env.DB, pageFolderId)
      if (!restoreFolderResult) {
        return c.json(result.error(500, 'Failed to restore folder'))
      }
    }

    if (await restorePage(c.env.DB, id)) {
      return c.json(result.success(null))
    }

    return c.json(result.error(500, 'Failed to restore page'))
  },
)

app.delete(
  '/clear_deleted',
  async (c) => {
    if (await clearDeletedPage(c.env.DB, c.env.BUCKET)) {
      return c.json(result.success(null))
    }
  },
)

app.get(
  '/content',
  validator('query', (value, c) => {
    if (isNil(value.pageId) || !isNumberString(value.pageId)) {
      return c.json(result.error(400, 'Page ID is required and should be a number'))
    }

    return {
      pageId: Number(value.pageId),
    }
  }),
  async (c) => {
    const { pageId } = c.req.valid('query')

    const page = await getPageById(c.env.DB, { id: pageId, isDeleted: false })
    if (isNil(page)) {
      return c.json(result.error(500, 'Page not found'))
    }

    const content = await c.env.BUCKET.get(page.contentUrl)
    if (!content) {
      return c.json(result.error(500, 'Page data not found'))
    }

    c.res.headers.set('cache-control', 'private, max-age=604800')
    return c.html(
      await content.text(),
    )
  },
)

// List archived historical snapshots for a page (metadata only).
app.get(
  '/versions',
  validator('query', (value, c) => {
    if (isNil(value.pageId) || !isNumberString(value.pageId)) {
      return c.json(result.error(400, 'Page ID is required and should be a number'))
    }
    return { pageId: Number(value.pageId) }
  }),
  async (c) => {
    const { pageId } = c.req.valid('query')
    const versions = await queryPageVersions(c.env.DB, pageId)
    return c.json(result.success(versions))
  },
)

// Serve the archived HTML of a specific historical version.
app.get(
  '/version_content',
  validator('query', (value, c) => {
    if (isNil(value.versionId) || !isNumberString(value.versionId)) {
      return c.json(result.error(400, 'Version ID is required and should be a number'))
    }
    return { versionId: Number(value.versionId) }
  }),
  async (c) => {
    const { versionId } = c.req.valid('query')
    const version = await getPageVersionById(c.env.DB, versionId)
    if (isNil(version)) {
      return c.json(result.error(404, 'Version not found'))
    }
    const content = await c.env.BUCKET.get(version.contentUrl)
    if (!content) {
      return c.json(result.error(404, 'Version data not found'))
    }
    c.res.headers.set('cache-control', 'private, max-age=604800')
    return c.html(await content.text())
  },
)

app.put(
  '/update_showcase',
  validator('json', (value, c) => {
    if (!value.id || typeof value.id !== 'number') {
      return c.json(result.error(400, 'Page ID is required and should be a number'))
    }

    if (typeof value.isShowcased !== 'number') {
      return c.json(result.error(400, 'isShowcased is required and should be a number'))
    }

    return {
      id: value.id,
      isShowcased: value.isShowcased,
    }
  }),
  async (c) => {
    const { id, isShowcased } = c.req.valid('json')
    const updateResult = await updateShowcase(c.env.DB, { id, isShowcased })

    return c.json(result.success(updateResult))
  },
)

app.get(
  '/screenshot',
  validator('query', (value, c) => {
    if (isNil(value.id) || typeof value.id !== 'string') {
      return c.json(result.error(400, 'ID is required'))
    }

    return {
      id: value.id,
    }
  }),
  async (c) => {
    const { id } = c.req.valid('query')

    const screenshot = await getFileFromBucket(c.env.BUCKET, id)

    c.res.headers.set('Content-Type', 'image/webp')
    c.res.headers.set('cache-control', 'private, max-age=31536000')

    if (isNil(screenshot)) {
      return c.body(null)
    }

    return c.body(await screenshot.arrayBuffer())
  },
)

export default app
